backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MarkdownPostLayout.astro"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "pubDate", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Imágen", name: "image", widget: "image"}
      - {label: "Etiquetas", name: "tags", widget: "tag"}
      - {label: "Body", name: "body", widget: "markdown"}